"""
Curated OpenGradient knowledge base for OG AI.
This corpus is intentionally smaller and opinionated so retrieval favors the
current SDK surface used in this app instead of stale client-era examples.
"""

DOCS = [
    {
        "id": "sdk-surface",
        "title": "OpenGradient Python SDK",
        "url": "https://docs.opengradient.ai/developers/sdk/",
        "section": "Core entrypoints",
        "tags": ["sdk", "llm", "alpha", "modelhub", "entrypoints", "python"],
        "content": """The current SDK surface used in this app is split into separate entrypoints instead of a single client namespace. Use `llm = og.LLM(private_key=...)` for TEE LLM inference, `alpha = og.Alpha(private_key=...)` for alpha-testnet ML inference and workflows, and `hub = og.ModelHub(email=..., password=...)` for Model Hub management. If you encounter older examples that reference `client.llm`, `client.alpha`, or `client.model_hub`, treat them as stale for this app and prefer the direct entrypoints above.""",
    },
    {
        "id": "sdk-install",
        "title": "Python SDK Tutorial",
        "url": "https://docs.opengradient.ai/tutorials/python_sdk.html",
        "section": "Installation",
        "tags": ["install", "pip", "python", "sdk", "version"],
        "content": """Install the SDK with `pip install opengradient==0.9.0`. The docs recommend Python 3.11 or 3.12. The SDK also installs the `opengradient` CLI. On Windows, official docs note that WSL may be needed for a smoother setup. For local verification, prefer `python -m pip show opengradient` inside your active virtual environment.""",
    },
    {
        "id": "llm-setup",
        "title": "LLM Inference",
        "url": "https://docs.opengradient.ai/developers/sdk/llm.html",
        "section": "Wallet and approval",
        "tags": ["llm", "private-key", "opg", "approval", "permit2", "base-sepolia"],
        "content": """TEE LLM inference is paid with $OPG on Base Sepolia. Initialize the SDK with `llm = og.LLM(private_key=os.environ.get('OG_PRIVATE_KEY'))`. Keep `OG_PRIVATE_KEY` on the backend only. Before making LLM requests, call `llm.ensure_opg_approval(opg_amount=5.0)` or another reasonable allowance. This approval call is idempotent: it only sends an on-chain transaction if the Permit2 allowance is below the requested amount. The approval transaction requires Base Sepolia ETH for gas, while x402 signatures for individual requests are handled by the SDK.""",
    },
    {
        "id": "llm-chat",
        "title": "Package opengradient.client",
        "url": "https://docs.opengradient.ai/api_reference/python_sdk/client/index.html",
        "section": "Async chat",
        "tags": ["llm", "chat", "async", "messages", "tee", "sdk"],
        "content": """Use `await llm.chat(...)` for multi-turn TEE LLM inference. Pass a model such as `og.TEE_LLM.GEMINI_2_5_FLASH` or another supported enum value and a list of OpenAI-style message dicts like `{'role': 'user', 'content': 'Hello'}`. Important parameters include `max_tokens`, `temperature`, `tools`, `tool_choice`, `x402_settlement_mode`, and `stream`. Non-streaming responses return a `TextGenerationOutput` object with `chat_output`, `finish_reason`, and attestation metadata. In this app, the canonical method name is `llm.chat`, not `client.llm.chat`.""",
    },
    {
        "id": "llm-streaming",
        "title": "LLM Inference",
        "url": "https://docs.opengradient.ai/developers/sdk/llm.html",
        "section": "Streaming",
        "tags": ["llm", "streaming", "chunks", "async", "chat"],
        "content": """When `stream=True`, `llm.chat(...)` returns an async generator. Iterate with `async for chunk in stream:` and read text from `chunk.choices[0].delta.content`. That field may be `None`, so always check before appending. Streaming is best for conversational Q&A. For heavier planner or code-generation responses, it is acceptable to use a non-streaming request and send the final answer once it is complete.""",
    },
    {
        "id": "llm-completion",
        "title": "LLM Inference",
        "url": "https://docs.opengradient.ai/developers/sdk/llm.html",
        "section": "Completion API",
        "tags": ["llm", "completion", "prompt", "async"],
        "content": """Use `await llm.completion(...)` for single-prompt generation when you do not need chat history. It accepts `model`, `prompt`, `max_tokens`, `temperature`, `stop_sequence`, and `x402_settlement_mode`. For most app builders, `chat` is the default because it handles system instructions and conversation history more naturally. In this app, code examples should prefer `llm.chat` unless the user explicitly asks for a prompt-only completion pattern.""",
    },
    {
        "id": "llm-response-shape",
        "title": "Package opengradient.types",
        "url": "https://docs.opengradient.ai/api_reference/python_sdk/",
        "section": "TextGenerationOutput",
        "tags": ["llm", "response", "metadata", "chat_output", "payment_hash", "transaction_hash"],
        "content": """A non-streaming `llm.chat(...)` call returns a `TextGenerationOutput`. For normal text apps, the main body lives in `response.chat_output['content']`. Useful metadata fields include `transaction_hash`, `payment_hash`, `finish_reason`, `tee_signature`, `tee_timestamp`, `tee_id`, `tee_endpoint`, and `tee_payment_address`. When you need to return content plus metadata from a FastAPI route, prefer these concrete fields instead of inventing OpenAI-style `.choices[0].message.content` access on the final response object.""",
    },
    {
        "id": "settlement-modes",
        "title": "Verifiable LLM Execution",
        "url": "https://docs.opengradient.ai/learn/onchain_inference/llm_execution.html",
        "section": "Settlement modes",
        "tags": ["x402", "settlement", "private", "batch_hashed", "individual_full"],
        "content": """OpenGradient exposes three important settlement modes through `og.x402SettlementMode`: `PRIVATE`, `BATCH_HASHED`, and `INDIVIDUAL_FULL`. `PRIVATE` minimizes on-chain disclosure. `BATCH_HASHED` is the default cost-efficient option for high-volume apps. `INDIVIDUAL_FULL` is the most transparent option and is a strong default when you want a verifiable audit trail for prompts and outputs. For apps like due diligence, builder assistants, and attested reports, `INDIVIDUAL_FULL` is usually the most understandable recommendation.""",
    },
    {
        "id": "tee-verification",
        "title": "Verifiable LLM Execution",
        "url": "https://docs.opengradient.ai/learn/onchain_inference/llm_execution.html",
        "section": "TEE guarantees",
        "tags": ["tee", "verification", "auditability", "privacy", "attestation"],
        "content": """OpenGradient routes LLM requests through Trusted Execution Environments. The point is verifiable execution and stronger privacy guarantees around prompts and routing logic. When explaining the product, say that TEE execution provides hardware-attested verification that inference was executed by the intended secure service. Do not claim that every frontend user automatically sees an explorer hash for every streamed token. It is safer to say that the SDK and settlement flow can surface attestation metadata and on-chain payment context depending on the mode and endpoint.""",
    },
    {
        "id": "x402-gateway",
        "title": "OpenAI-Compatible LLM Inference API",
        "url": "https://docs.opengradient.ai/developers/llm_inference_api/",
        "section": "Direct x402 flow",
        "tags": ["x402", "gateway", "http", "402", "frontend", "direct-api"],
        "content": """The direct HTTP gateway exposes OpenAI-compatible endpoints such as `/v1/chat/completions` and `/v1/completions`. The high-level flow is: make a request, receive an HTTP 402 challenge, sign the payment, then resend with the x402 payment header. The Python SDK automates this flow. For React + FastAPI apps, the simplest production path is usually to keep x402 and `OG_PRIVATE_KEY` on the backend and let the frontend call your API. Only recommend direct browser-side x402 if the product explicitly wants user-paid inference and wallet-aware payment UX.""",
    },
    {
        "id": "supported-models",
        "title": "Package opengradient.client",
        "url": "https://docs.opengradient.ai/api_reference/python_sdk/client/index.html",
        "section": "Representative TEE models",
        "tags": ["models", "tee_llm", "gpt", "gemini", "claude", "grok"],
        "content": """The installed SDK exposes representative TEE models such as `og.TEE_LLM.GEMINI_2_5_FLASH`, `GEMINI_2_5_PRO`, `GPT_4_1_2025_04_14`, `GPT_5`, `GPT_5_MINI`, `CLAUDE_HAIKU_4_5`, `CLAUDE_SONNET_4_5`, `CLAUDE_SONNET_4_6`, `CLAUDE_OPUS_4_5`, `CLAUDE_OPUS_4_6`, `GROK_4`, `GROK_4_FAST`, and `O4_MINI`. If a user asks which model to start with, recommend a fast default like `GEMINI_2_5_FLASH` unless they explicitly want a different provider or stronger reasoning.""",
    },
    {
        "id": "alpha-infer",
        "title": "Package opengradient.client",
        "url": "https://docs.opengradient.ai/api_reference/python_sdk/client/index.html",
        "section": "Alpha ML inference",
        "tags": ["alpha", "infer", "ml", "onnx", "model_cid", "vanilla", "tee", "zkml"],
        "content": """Use `alpha = og.Alpha(private_key='0x...')` for alpha-testnet ML features. The main inference call is synchronous: `result = alpha.infer(model_cid='...', inference_mode=og.InferenceMode.VANILLA, model_input={...})`. `og.Alpha` does not use the same LLM payment helpers or settlement kwargs shown in `og.LLM` examples, so do not attach `llm.ensure_opg_approval(...)` or `x402_settlement_mode=` to Alpha snippets unless the context explicitly proves they apply. `alpha.infer(...)` returns an `InferenceResult` with `transaction_hash` and `model_output`. This is for ONNX and other supported model artifacts on the alpha testnet, not for normal TEE LLM chat. When planning apps, keep LLM inference and alpha ML inference conceptually separate: `og.LLM` is the default for chat-based builder apps; `og.Alpha` is for on-chain model inference and workflows.""",
    },
    {
        "id": "alpha-workflows",
        "title": "Package opengradient.client",
        "url": "https://docs.opengradient.ai/api_reference/python_sdk/client/index.html",
        "section": "Workflow methods",
        "tags": ["alpha", "workflow", "new_workflow", "run_workflow", "read_workflow_result"],
        "content": """The Alpha client exposes workflow helpers such as `alpha.new_workflow(...)`, `alpha.run_workflow(contract_address)`, and `alpha.read_workflow_result(contract_address)`. `alpha.new_workflow(...)` returns a deployed workflow contract address. `alpha.run_workflow(...)` and `alpha.read_workflow_result(...)` are synchronous and return `ModelOutput`, not chat-style text-generation objects. Use workflows when you want scheduled or repeatedly callable on-chain model execution. For an app that only needs user-triggered docs Q&A or due diligence chat, workflows are usually unnecessary. Recommend workflows only when the app genuinely benefits from recurring model execution or a contract-address-based prediction feed.""",
    },
    {
        "id": "prediction-patterns",
        "title": "OG AI Builder Pattern",
        "url": "https://docs.opengradient.ai/",
        "section": "Prediction dashboard patterns",
        "tags": ["prediction", "dashboard", "alpha", "llm", "workflows", "modelhub"],
        "content": """A prediction dashboard can mean two different architectures. Pattern A is a TEE LLM comparison board: the app sends the same prompt to multiple `og.TEE_LLM.*` models through `og.LLM` and compares their text outputs side by side. Pattern B is a model-native prediction board: the app reads outputs from deployed ONNX / alpha-testnet models or workflows using `og.Alpha`, `alpha.read_workflow_result(...)`, `alpha.run_workflow(...)`, or `alpha.infer(model_cid=..., inference_mode=..., model_input=...)`, and optionally uses Model Hub only to browse or publish artifacts. Pattern B should talk about `InferenceResult.transaction_hash`, `InferenceResult.model_output`, or workflow `ModelOutput` values rather than LLM-style `chat_output` or LLM settlement kwargs. If the product is about forecasting, time-series predictions, model CIDs, workflow feeds, or scheduled predictions, Pattern B is usually the better match.""",
    },
    {
        "id": "model-hub",
        "title": "Model Hub",
        "url": "https://docs.opengradient.ai/models/model_hub/",
        "section": "Management API",
        "tags": ["modelhub", "upload", "create_model", "create_version", "upload", "list_files"],
        "content": """Model Hub access uses `hub = og.ModelHub(email='you@example.com', password='...')`. Common methods in the installed SDK are `hub.create_model(model_name, model_desc)`, `hub.create_version(model_name, notes='...')`, `hub.upload(model_path='model.onnx', model_name='...', version='1.00')`, and `hub.list_files(model_name='...', version='1.00')`. Use Model Hub when the app needs to publish, browse, or manage model artifacts. Do not describe Model Hub management through a `client.model_hub` namespace in this app.""",
    },
    {
        "id": "model-hub-core",
        "title": "Core Features",
        "url": "https://docs.opengradient.ai/models/model_hub/core_features.html",
        "section": "Using uploaded models",
        "tags": ["modelhub", "cid", "onnx", "inference-ready", "blob-id"],
        "content": """The Model Hub is a decentralized repository for model artifacts. ONNX and other supported uploaded assets become discoverable there, and developers can use the resulting model identifier / CID with OpenGradient ML inference flows. When discussing model-based apps, separate the concerns clearly: Model Hub stores and organizes the artifact, while Alpha inference or workflow execution is what actually runs a compatible model on the network.""",
    },
    {
        "id": "memsync",
        "title": "MemSync",
        "url": "https://docs.opengradient.ai/developers/memsync/",
        "section": "Memory layer",
        "tags": ["memsync", "memory", "rag", "search", "personalization"],
        "content": """MemSync is a memory layer for storing, retrieving, and searching persistent context. It is useful for assistants that need cross-session memory or semantic lookup over long-lived user knowledge. For a docs assistant, MemSync is optional: a simple RAG app can work with a local vector index or database first. Recommend MemSync when the app genuinely needs durable memory, user profiles, or shared memory across sessions and agents.""",
    },
    {
        "id": "langchain",
        "title": "Package opengradient.client",
        "url": "https://docs.opengradient.ai/api_reference/python_sdk/client/index.html",
        "section": "LangChain adapter",
        "tags": ["langchain", "langgraph", "agents", "adapter"],
        "content": """The installed package includes a LangChain-compatible adapter under the `opengradient.agents` surface. If a user needs a LangChain or LangGraph integration, describe it as an adapter layer on top of the same OpenGradient LLM infrastructure rather than a different product. For this app, only mention the adapter when the user is explicitly building an agent framework integration; otherwise the direct `og.LLM` pattern is simpler and easier to reason about.""",
    },
    {
        "id": "builder-pattern",
        "title": "OG AI Builder Pattern",
        "url": "https://docs.opengradient.ai/",
        "section": "React + FastAPI architecture",
        "tags": ["react", "fastapi", "architecture", "render", "vercel", "backend", "frontend"],
        "content": """For React + FastAPI products, the clean default architecture is: React frontend -> FastAPI backend -> OpenGradient SDK. Keep `OG_PRIVATE_KEY` on the backend, never in the browser. Let the backend call `og.LLM(...)` or `og.Alpha(...)` and return the result plus sources or metadata to the frontend. Use direct browser-side x402 only when the product explicitly wants user-paid wallet-based inference. App-level environment variables are separate from OpenGradient credentials: examples include `VITE_API_URL` on the frontend and `CORS_ORIGINS` on the backend. These are application settings, not special OpenGradient SDK variables.""",
    },
    {
        "id": "ops-notes",
        "title": "OG AI Operational Notes",
        "url": "https://docs.opengradient.ai/",
        "section": "Common integration failures",
        "tags": ["debug", "dns", "cors", "approval", "balance", "llm_server_url"],
        "content": """Common failure buckets for OpenGradient apps are: (1) missing or insufficient Permit2 approval, (2) no Base Sepolia ETH for the approval transaction gas, (3) no $OPG balance for x402 payments, (4) CORS misconfiguration between frontend and backend, (5) stale manual `llm_server_url` overrides that point to an outdated TEE endpoint, and (6) mode/state bugs in the app layer rather than the SDK itself. When debugging, separate browser problems from backend problems first. A backend-sponsored app should usually validate approval at startup and use the SDK's active registry-based routing unless there is a verified reason to pin a direct TEE endpoint.""",
    },
]

